name: Build and Publish Libraries

on:
  workflow_dispatch: 
    inputs:
        language:
          description: 'Select the programming language'
          required: true
          type: choice
          options:
            - Python
            - JavaScript
            - Go
            - Java
        versionType:
          description: 'Version type to increment'
          required: true
          type: choice
          options:
            - major
            - minor
            - patch
          default: minor

jobs:
  build-and-publish-java:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.language=='Java'}}

    permissions:
      contents: write
      packages: write  # Write access for publishing to GitHub Packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Echo selected language
        run: |
          echo The entered value ${{github.events.inputs.language}}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get current version
        working-directory: cicd-java
        id: get_current_version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV

      - name: Echo the current version
        run: echo "The current version of cicd-java is ${{ env.CURRENT_VERSION }}"

      - name: Increment Java version
        working-directory: cicd-java
        id: increment_java_version
        run: |
          version="${{ env.CURRENT_VERSION }}"
          IFS='.' read -r major minor patch <<< "$version" 

          case "${{ github.event.inputs.versionType}}" in
            major)
              major=$((major+1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor+1))
              patch=0
              ;;
            patch)
              patch=$((patch+1))
              ;;
          esac

          new_version="$major.$minor.$patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
        
      - name: Echo the new version
        run: echo "The new version is ${{ env.NEW_VERSION }}"

      - name: Update the version in pom.xml
        working-directory: cicd-java
        run: |
          mvn versions:set -DnewVersion=${{ env.NEW_VERSION }}
      
      - name: Check new version
        working-directory: cicd-java
        id: check_new
        run: |
          latest_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Echo the new version again
        run: echo "The new version from pom.xml is ${{ env.LATEST_VERSION }}"

      - name: Configure git
        working-directory: cicd-java
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Tag and Commit changes
        working-directory: cicd-java
        run: |
          git add pom.xml
          git commit -m "Bump Java version to ${{ env.NEW_VERSION }}"
          echo "TAG=learn-${{github.event.inputs.language}}-v${{env.NEW_VERSION}}" >> $GITHUB_ENV
          git tag -a learn-${{github.event.inputs.language}}-v${{env.NEW_VERSION}} -m "Release ${{ env.NEXT_VERSION }} for ${{ github.event.inputs.language }}"
          git push origin HEAD --tags

      - name: Build and Publish to GitHub Packages
        working-directory: cicd-java
        run: mvn clean install deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create GitHub release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}  
          release_name: Release ${{ env.TAG }}
          body: |
            ## Changes
            - Release of ${{ env.TAG }}
          draft: false
          prerelease: false
  
  build-and-publish-javascript:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.language=='JavaScript'}}

    permissions:
      contents: write
      packages: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        working-directory: cicd-js
        run: npm install
      
      - name: Get current version
        working-directory: cicd-js
        run: |
          current_version=$(node -p "require('./package.json').version")
          echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV
      
      - name: Echo the current version
        run: echo "The current version of cicd-js is ${{ env.CURRENT_VERSION }}"

      - name: Increment Javascript version
        working-directory: cicd-js
        id: increment_java_version
        run: |
          version="${{ env.CURRENT_VERSION }}"
          IFS='.' read -r major minor patch <<< "$version" 

          case "${{ github.event.inputs.versionType}}" in
            major)
              major=$((major+1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor+1))
              patch=0
              ;;
            patch)
              patch=$((patch+1))
              ;;
          esac

          new_version="$major.$minor.$patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Echo the new version
        run: echo "The new version is ${{ env.NEW_VERSION }}"

      - name: Update the version in package.jsom
        working-directory: cicd-js
        run: |
          npm version $NEW_VERSION --no-git-tag-version 
        
      - name: Confirm updated package.json version 
        working-directory: cicd-js
        run: |
          latest_version=$(node -p "require('./package.json').version")
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV
          echo "The new version from package.json is ${{ env.LATEST_VERSION }}"

      - name: Configure git
        working-directory: cicd-js
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Tag and Commit changes
        working-directory: cicd-js
        run: |
          git add ./package.json
          git add ./package-lock.json
          git commit -m "Bump Javascript version to ${{ env.NEW_VERSION }}"
          echo "TAG=learn-${{github.event.inputs.language}}-v${{env.NEW_VERSION}}" >> $GITHUB_ENV
          git tag -a learn-${{github.event.inputs.language}}-v${{env.NEW_VERSION}} -m "Release ${{ env.NEXT_VERSION }} for ${{ github.event.inputs.language }}"
          git push origin HEAD --tags
      
